name: "Build NixOS configuration"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        machine:
          - host: rigil
            platform: x86-64-linux
          - host: proxima
            platform: x86-64-linux
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - uses: cachix/cachix-action@v17
        with:
          name: heather7283
          # Part of the key AFTER the colon (this also applies to public key)
          # To register a public key in cachix without using their CLI do this:
          # curl -i -X POST \
          #    -H "Authorization: Bearer PersonalAuthToken" \
          #    -H "Content-Type: application/json" \
          #    -d '{ "publicKey": "key-after-the-colon-very-important" }' \
          #    https://app.cachix.org/api/v1/cache/cache-name/key
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # Nice 800+ MB .jar bro
          pushFilter: '^.*[jJ][mM]usic[bB]ot.*$'

      - name: Fixup git URLs
        run: |
          git config --global \
            url.'https://${{ secrets.GH_TOKEN }}@github.com'.insteadOf 'ssh://git@github.com'

      - name: Build NixOS configuration
        run: |
          nix build .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel

